"""HT-CN harmonic core.

This package contains deterministic geometry and source-backed harmonic lifecycle audits.
A-share context and trading decisions must live outside this namespace so they cannot mutate
Carney pattern identity.
"""

from .abcd import (
    ABCDCheck,
    ABCDEvaluation,
    ABCDFormingMatch,
    ABCDMatch,
    ABCDMetrics,
    ABCDProjection,
    evaluate_abcd,
    forming_abc_points,
    iter_abcd_points,
    measure_abcd,
    project_forming_abcd,
    scan_abcd_pivots,
    scan_forming_abcd_pivots,
)
from .candidates import (
    SwingWindow,
    iter_completed_xabcd_windows,
    iter_forming_xabc_windows,
    iter_swing_windows,
)
from .engine import CompletedMatch, FormingMatch, HarmonicScan, scan_frame, scan_pivots
from .evaluator import (
    ConstraintCheck,
    PatternEvaluation,
    XABCDMetrics,
    evaluate_xabcd,
    measure_xabcd,
)
from .five_zero import (
    FiveZeroEvaluation,
    FiveZeroFormingMatch,
    FiveZeroMatch,
    FiveZeroMetrics,
    FiveZeroProjection,
    evaluate_five_zero,
    measure_five_zero,
    project_forming_five_zero,
    scan_five_zero_pivots,
)
from .indicators import wilder_rsi
from .lifecycle import ReactionAudit, audit_completed_reaction
from .models import (
    HarmonicPoint,
    PatternDirection,
    PatternState,
    Pivot,
    PivotKind,
    RatioMeasurement,
)
from .pivots import (
    build_pivot_consensus,
    collapse_same_kind_pivots,
    detect_confirmed_pivots,
    detect_multi_scale_pivots,
)
from .prz import PRZComponent, PotentialReversalZone, build_xabcd_prz
from .ratios import RECIPROCAL_ABCD, leg_length, ratio_of_legs, reciprocal_bc_targets
from .rsi_bamm import (
    RSI_BAMM_PERIOD,
    RSI_BAMM_SOURCE_DEFINITION,
    RSIBammConfirmation,
    RSIBammDirection,
    RSIBammProfile,
    RSIBammRelation,
    RSIBammSequence,
    RSIBammStructure,
    RSIBammStructureKind,
    confirm_rsi_bamm,
    scan_rsi_bamm_frame,
    scan_rsi_bamm_values,
)
from .rules import CARNEY_RULES, PatternRule, RatioConstraint
from .scanner import (
    FormingPattern,
    classify_completed_xabcd,
    executable_xabcd_rules,
    project_forming_xabcd,
)
from .shark import (
    SharkEvaluation,
    SharkFormingMatch,
    SharkMatch,
    SharkMetrics,
    SharkProjection,
    evaluate_shark,
    measure_shark,
    project_forming_shark,
    scan_shark_pivots,
)

__all__ = [
    "ABCDCheck",
    "ABCDEvaluation",
    "ABCDFormingMatch",
    "ABCDMatch",
    "ABCDMetrics",
    "ABCDProjection",
    "CARNEY_RULES",
    "RECIPROCAL_ABCD",
    "CompletedMatch",
    "ConstraintCheck",
    "FiveZeroEvaluation",
    "FiveZeroFormingMatch",
    "FiveZeroMatch",
    "FiveZeroMetrics",
    "FiveZeroProjection",
    "FormingMatch",
    "FormingPattern",
    "HarmonicPoint",
    "HarmonicScan",
    "PRZComponent",
    "PatternDirection",
    "PatternEvaluation",
    "PatternRule",
    "PatternState",
    "Pivot",
    "PivotKind",
    "PotentialReversalZone",
    "RSI_BAMM_PERIOD",
    "RSI_BAMM_SOURCE_DEFINITION",
    "RSIBammConfirmation",
    "RSIBammDirection",
    "RSIBammProfile",
    "RSIBammRelation",
    "RSIBammSequence",
    "RSIBammStructure",
    "RSIBammStructureKind",
    "RatioConstraint",
    "RatioMeasurement",
    "ReactionAudit",
    "SharkEvaluation",
    "SharkFormingMatch",
    "SharkMatch",
    "SharkMetrics",
    "SharkProjection",
    "SwingWindow",
    "XABCDMetrics",
    "audit_completed_reaction",
    "build_pivot_consensus",
    "build_xabcd_prz",
    "classify_completed_xabcd",
    "collapse_same_kind_pivots",
    "confirm_rsi_bamm",
    "detect_confirmed_pivots",
    "detect_multi_scale_pivots",
    "evaluate_abcd",
    "evaluate_five_zero",
    "evaluate_shark",
    "evaluate_xabcd",
    "executable_xabcd_rules",
    "forming_abc_points",
    "iter_abcd_points",
    "iter_completed_xabcd_windows",
    "iter_forming_xabc_windows",
    "iter_swing_windows",
    "leg_length",
    "measure_abcd",
    "measure_five_zero",
    "measure_shark",
    "measure_xabcd",
    "project_forming_abcd",
    "project_forming_five_zero",
    "project_forming_shark",
    "project_forming_xabcd",
    "ratio_of_legs",
    "reciprocal_bc_targets",
    "scan_abcd_pivots",
    "scan_five_zero_pivots",
    "scan_forming_abcd_pivots",
    "scan_frame",
    "scan_pivots",
    "scan_rsi_bamm_frame",
    "scan_rsi_bamm_values",
    "scan_shark_pivots",
    "wilder_rsi",
]
